### ISSUE TITLE
Feature request: add support for jumping to json node by specific path.

### ISSUE THREAD

**Issue by wufeng87** [apihero-run/jsonhero-web#100]
Say I already open the json I need to view, and I got the path I want to jump to from another colleague, and I want to jump to this path without reload my page.

It's more effective than using the search bar to search and navigate.

**Comment by Suven-p** [comment]
Can I work on this?

**Comment by ericallam** [comment]
Sure, go for it!

**Comment by matt-aitken** [comment]
@Suven-p you'll see we’re using paths a lot in the code already to navigate. Using https://www.npmjs.com/package/@jsonhero/path

**Comment by Suven-p** [comment]
I thought of having the [PathBarLink](https://github.com/apihero-run/jsonhero-web/blob/478f41f45ec7ee468442880135b6ca40e098fb30/app/components/PathBar.tsx#L31) have text mode and gui mode. 
Go into text mode by double clicking path bar.
When focus moves out of path bar switch directory and switch back to GUI mode.

Something like these
![image](https://user-images.githubusercontent.com/47393058/192472965-241a1c93-0ffd-4b5d-98b8-201be4508e6a.png)
![image](https://user-images.githubusercontent.com/47393058/192473090-24e4068c-0458-44b7-8072-d4f5eb688755.png)

Would that work?

**Comment by matt-aitken** [comment]
I like the idea of it being edited in the path bar. The only issue with double click is it seems a shame that such a useful feature is hidden behind a hidden gesture. What if we had an edit button to the right of the path bar that turns it into a textfield like you suggested. When in text editing mode that button turns into a tick to commit? (Return/Enter on the keyboard would also commit). What do you think?

**Comment by Suven-p** [comment]
Yes that makes sense. Would it be ok if I make the PR in October for hacktoberfest? aiming for October first :)

**Comment by matt-aitken** [comment]
That sounds great 👍

**Comment by Suven-p** [comment]
Deployed to https://json.nevus.workers.dev/ from https://github.com/Suven-p/jsonhero-web/commit/1b16beb6792c566f9600975efac7d2843923d638

**Comment by ericallam** [comment]
This looks great! Would love a PR when you get a chance
