### ISSUE TITLE
Bug: Switching to JSON view creates a weird padding at the bottom of the page.

### ISSUE THREAD

**Issue by ShaneMaglangit** [apihero-run/jsonhero-web#109]
While working on another issue, I noticed that a weird padding pops up on the bottom of the page whenever the JSON View is opened.

**Steps to replicate**

1. Load the json page with Column View
2. Switch to JSON View

**Before**

![image](https://user-images.githubusercontent.com/53674742/193532892-58a9e083-122c-42da-bebb-58bd6217b000.png)

**After**

![image](https://user-images.githubusercontent.com/53674742/193532964-f0072e2e-3300-4ba5-af7e-4727b256237b.png)

**OS**: Windows 11
**Browser**: Chrome

**Comment by WaunBroderick** [comment]
Hey @ericallam mind if I take on this task?

**Comment by ericallam** [comment]
@WaunBroderick go for it!

**Comment by WaunBroderick** [comment]
Awesome thanks @ericallam , pull request submitted.
