### ISSUE TITLE
Add an easy way to copy the entire JSON or download it

### ISSUE THREAD

**Issue by AndrianBalanescu** [apihero-run/jsonhero-web#115]
Please add this feature.

**Comment by Suven-p** [comment]
What would be the appropriate place to put the download button?

**Comment by Suven-p** [comment]
There's a way to copy entire json. On the left side where the json is displayed you can hover on it to find the copy button.
![image](https://user-images.githubusercontent.com/47393058/194732412-a9fc9e54-b97b-44ba-b71b-451b035998ac.png)

There is another copy button under path which also appears on hover. This is not what you are looking for but it might be confusing.
![image](https://user-images.githubusercontent.com/47393058/194732471-73e8383c-b82d-4d9b-a874-e078e4e0e606.png)

**Comment by ericallam** [comment]
Yea I've wanted a "View Raw JSON" button in the past, not sure where it would go though. There is a little known feature that if you add `.json` to the url it displays the raw JSON so we could use that.

**Comment by Suven-p** [comment]
![image](https://user-images.githubusercontent.com/47393058/194762068-9f1b0db9-aa09-4f6b-aaa2-b9a6b5ba8635.png)
Would this work? IMO it isn't great.

**Comment by ericallam** [comment]
![CleanShot 2022-10-09 at 16 12 57@2x](https://user-images.githubusercontent.com/534/194764638-bc93863a-5978-406a-a307-63bbdbcb3e7f.png)

Why don't we replace this icon with the download icon and make that a `<a target="_blank">` to the path with `.json` appended?
