### ISSUE TITLE
Add ability to jump from a `$ref` to the location in the document if it exists

### ISSUE THREAD

**Issue by ericallam** [apihero-run/jsonhero-web#121]
Example:

https://jsonhero.io/j/tRO2RzV5zfa7?path=%24.paths.%2F2%2Ftweets%2F%7Bid%7D.get.parameters.0.%24ref

**Comment by Prasaya** [comment]
![Screenshot from 2022-10-13 20-47-01](https://user-images.githubusercontent.com/47562404/195634622-85d66660-48f7-4258-aa80-f77001bca893.png)
I plan to redirect when the user clicks on the value part. Would that work?

Should the redirect work only when the key value is $ref? What should be the behaviour when the path does not exist?

**Comment by ericallam** [comment]
Yea I think the key has to be `$ref`, and I think nothing should happen if the path does not exist (or check the path exists before making the ref value a link?
