### ISSUE TITLE
Add skeleton loader to preview section to prevent content jumping

### ISSUE THREAD

**Issue by ericallam** [apihero-run/jsonhero-web#38]
https://www.smashingmagazine.com/2020/04/skeleton-screens-react/

**Comment by Cool-Runningz** [comment]
Hey 👋🏽 @ericallam, I am interested in working on this. Is this still up for grabs??

**Comment by ericallam** [comment]
Yup go for it!

**Comment by Cool-Runningz** [comment]
Thanks for the opportunity to contribute!  I did have one question about the placement of the skeleton loader...

The title of the issue mentions the "preview" section. Is that referring to the individual columns for each respective view when the data is initially loaded in? My assumption is that you want the loader visible anywhere data is being processed but just wanted to confirm.

**Comment by ericallam** [comment]
It refers to the right hand side bar, where we display images or sometimes information about a website url

**Comment by ericallam** [comment]
![CleanShot 2022-10-08 at 20 16 05@2x](https://user-images.githubusercontent.com/534/194723906-f5cb00fb-0fee-4086-9820-f095d4ef31be.png)

**Comment by Cool-Runningz** [comment]
Great, thanks for the clarification! I was able to locate it and am working on a fix now.
