### ISSUE TITLE
Feature Request: Dockerfile / Official docker images

### ISSUE THREAD

**Issue by DocBrown101** [apihero-run/jsonhero-web#73]
It would be very helpful to me if you could ship a Dockerfile and build official images.

Thanks for creating this project!

**Comment by ericallam** [comment]
We now have a Dockerfile in the repo [here](https://github.com/apihero-run/jsonhero-web/blob/main/Dockerfile). Please let me know if that solves your use case

**Comment by henryclw** [comment]
@DocBrown101 Hi Daniel, there isn't a official image on docker hub, but I've set up my own everyday build image on my docker hub, feel free to use it.

<https://hub.docker.com/r/henryclw/jsonhero-web>

[![Docker Pulls](https://img.shields.io/docker/pulls/henryclw/jsonhero-web)](https://hub.docker.com/r/henryclw/jsonhero-web)    [![Docker Image Size (tag)](https://img.shields.io/docker/image-size/henryclw/jsonhero-web/latest)](https://hub.docker.com/r/henryclw/jsonhero-web)    [![Build and Publish Docker Image](https://github.com/henryclw/jsonhero-web/actions/workflows/docker-image.yml/badge.svg)](https://github.com/henryclw/jsonhero-web/actions/workflows/docker-image.yml)

**Comment by DocBrown101** [comment]
@henryclw Thank you, I will do that!

**Comment by DocBrown101** [comment]
@henryclw Do you have a git repository for your Docker image?

It seems that a build has to be created locally first, which does not work if you use read only images.

![image](https://user-images.githubusercontent.com/11892773/203921111-042d4141-6d0e-4c53-aca4-cab089322977.png)

**Comment by henryclw** [comment]
> @henryclw Do you have a git repository for your Docker image?
> 
> It seems that a build has to be created locally first, which does not work if you use read only images.
> 
> ![image](https://user-images.githubusercontent.com/11892773/203921111-042d4141-6d0e-4c53-aca4-cab089322977.png)

Yes, my GitHub repo is <https://github.com/henryclw/jsonhero-web>

Could you give more details of how to produce this error logs you posted? So that we could figure out what happened.
