### ISSUE TITLE
Nit: cursor should be pointer, not text, over JSON selector UI

### ISSUE THREAD

**Issue by samdutton** [apihero-run/jsonhero-web#85]
Currently, a text pointer is displayed over the text in the JSON selection/upload UI.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/205226/189141834-535a5006-f8f0-4356-b075-4d53ae5b5d5f.png">

The cursor should be a pointer over the whole container, including the text.

Great project btw! 👍🙏👏

**Comment by raheelrjunaid** [comment]
I can take this if it is available 😃

**Comment by ericallam** [comment]
@raheelrjunaid go for it 👍

**Comment by samdutton** [comment]
Thanks all!
