### ISSUE TITLE
[feature request] provides timestamp preview

### ISSUE THREAD

**Issue by setop** [apihero-run/jsonhero-web#87]
A date can be encoded as an int, as the number of second from epoch.

```json
{
  "d1": "2022-09-10 10:19:05+02:00",
  "d2": 1662798100
}
```

Like rfc-3339 string are displayed in a calendar, it would be nice to have the same preview for timestamp.

Cheers

**Comment by ShaneMaglangit** [comment]
@setop My concern is that we have no way of determining whether the value is a timestamp or really just a large integer.

**Comment by ericallam** [comment]
Ah yes, I see what the issue is. We actually already do this for strings that have numbers inside of them (see [here](https://github.com/apihero-run/json-infer-types/blob/main/src/formats/timestamp.ts)) but not for ints. We should extend json-infer-types to do the same thing for number types: https://github.com/apihero-run/json-infer-types

**Comment by setop** [comment]
Good question @ShaneMaglangit .

I don't know if it is part of the user experience jsonhero wants to give to it's user, but maybe there could like a toggle button "interpret this as a date" and it would be valid for this field for the current session.

Or, like @ericallam suggested, it could be inferred. from the key name : "date", "created_at", "updated_at", "*_at", "timestamp", etc. And/Or from the value,  like "a 10 digit integer with the first digit being a 1".

Or a mix of inference and toggle.

In any case, I'm convinced it would be really useful for the user cause "number of seconds since epoch" is so obscure to human brain. Who would say "now is 1664963535" or "I'm born 261266400" ?

**Comment by ericallam** [comment]
I think we should try to infer from the value, similar to how we are currently doing it with strings. Definitely against any kind of option like that
